# Generated by Django 5.0.7 on 2024-07-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_alter_cliente_table_alter_fornecedor_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientebkp',
            name='cidcli',
            field=models.CharField(max_length=50, verbose_name='Cidade do Cliente'),
        ),
        migrations.AlterField(
            model_name='clientebkp',
            name='cnpjcli',
            field=models.CharField(max_length=20, verbose_name='CNPJ do Cliente'),
        ),
        migrations.AlterField(
            model_name='clientebkp',
            name='codcli',
            field=models.CharField(max_length=10, verbose_name='Código do Cliente'),
        ),
        migrations.AlterField(
            model_name='clientebkp',
            name='estcli',
            field=models.CharField(max_length=100, verbose_name='Estado do Cliente'),
        ),
        migrations.AlterField(
            model_name='clientebkp',
            name='fonecli',
            field=models.CharField(max_length=20, verbose_name='Telefone do Cliente'),
        ),
        migrations.AlterField(
            model_name='clientebkp',
            name='idcli',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Cliente'),
        ),
        migrations.AlterField(
            model_name='clientebkp',
            name='nomecli',
            field=models.CharField(max_length=100, verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='clientebkp',
            name='razasoccli',
            field=models.CharField(max_length=100, verbose_name='Razão Social do Cliente'),
        ),
    ]
